name: Mirror to GitLab
on: [push]  # Triggers on every push to any branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone (avoids shallow push errors)

      - name: Push to GitLab
        run: |
          git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/ameypsawant/ollama_colab_server.git
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "actions@github.com"
          git push gitlab HEAD:main --force-with-lease