name: Mirror to GitLab
on: [push, create]  # Triggers on pushes AND new branches/tags

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to GitLab
        run: |
          git remote add gitlab https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@gitlab.com/${GITLAB_REPO}.git
          git push --mirror gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_USERNAME: "ameypsawant"
          GITLAB_REPO: "ameypsawant/ollama_colab_server"