name: Mirror to GitLab
on: [push, create]  # Triggers on pushes AND new branches/tags

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone required for mirroring

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "actions@github.com"

      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/ameypsawant/ollama_colab_server.git
          # Push branches and tags separately to avoid hidden refs
          git push gitlab --all --force
          git push gitlab --tags --force
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}